services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    build: .
    container_name: mariadb_conference
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
    networks:
      - mariadb_net

networks:
  mariadb_net:
    driver: bridge
